### ISSUE TITLE
Investigate AWS Rekognition for facial comparison capabilities 

### ISSUE THREAD

**Issue by M-Davies** [M-Davies/eye-of-horus#1]
# Why?

AWS provides more powerful and refined services than local python libraries for a reasonable cheap, if not free, price. Albeit harder to set up and understand initially, it'll save me a lot of development time later into the project

# Aims
Investigate AWS Rekognition, mainly following [this tutorial](https://docs.aws.amazon.com/rekognition/latest/dg/streaming-video.html) to produce a prototype script. Collect video evidence to confirm it works.

This script would take in a video stream (from my laptop or phone camera) and compare the faces in it to stored images on an AWS bucket. The response would be similar to the [examples here](https://docs.aws.amazon.com/rekognition/latest/dg/API_CompareFaces.html). A successful test would be a positive match with my face stored in AWS to a group of faces in the video stream.

**Comment by M-Davies** [comment]
# Steps
**Crossed means completed, un-crossed means in-progress**
- [x] Ensure AWS can handle multiple faces at obscure angles and poor image qualities. Completed by testing a custom image in the [example demo](https://us-east-2.console.aws.amazon.com/rekognition/home?region=us-east-2#/face-comparison):
<img width="1138" alt="Screenshot 2020-11-27 at 14 21 59" src="https://user-images.githubusercontent.com/25231953/101245055-2a0eb000-3702-11eb-9628-1efcb822a166.png">
- [x] Follow the 1st two steps of the [AWS Rekognition Getting Started Guide](https://docs.aws.amazon.com/rekognition/latest/dg/getting-started.html) - [Setting up an Account]. Completed by setting up an account with multiple IAM (Identity Access Management) users to segregate the cloud service users from each other, ensuring that nothing critical is run on the root or Admin accounts. I have also set up the [aws-cli](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html) to interact with the cloud services from my PC and python (of which I installed the [AWS Python SDK](https://aws.amazon.com/tools/) to do that).
- [ ] Begin installing dependencies that are needed for Rekognition. This involves following the relevant guide in https://docs.aws.amazon.com/rekognition/latest/dg/get-started-exercise.html (in my case, [Working with streaming videos](https://docs.aws.amazon.com/rekognition/latest/dg/streaming-video.html))

**Comment by M-Davies** [comment]
Amazon kinesis and streaming services setup using guide => https://docs.aws.amazon.com/rekognition/latest/dg/setting-up-your-amazon-rekognition-streaming-video-resources.html

Proceeding to prosecute plugin setup for streaming from device camera => https://docs.aws.amazon.com/rekognition/latest/dg/streaming-using-gstreamer-plugin.html

**Comment by M-Davies** [comment]
Plugin setup, I can now stream video from my device (a macbook) to AWS.

Now proceeding to [read](https://docs.aws.amazon.com/rekognition/latest/dg/streaming-video-kinesis-output.html) and [analyse](https://docs.aws.amazon.com/rekognition/latest/dg/using-rekognition-video-stream-processor.html) the results to try and get facial recog working

**Comment by M-Davies** [comment]
Read and analysis is working after a small hiccup with the role permissions (solved using [this guide section](https://docs.aws.amazon.com/rekognition/latest/dg/streaming-video-troubleshooting.html#ts-configured-sp) to rejig my role permissions). 

I can now stream video to the cloud and have it analysed, returning the result with a confidence match to the stored face in aws. I will attempt to replicate this success with Python scripts, since that will be the main method of communication between the backend and AWS

**Comment by M-Davies** [comment]
I am unsure if Python scripts will be the best solution for analysing the results due to the differences between NodeJS and Python. The NodeJS backend will need to be able to execute the python scripts in order to deploy assets and conduct investigations on the video streams.

While I feel comfortable that this should be possible [after looking online](https://stackoverflow.com/questions/23450534/how-to-call-a-python-function-from-node-js), I think I may likely have dependancy issues and problems with feedbacking to the user when something goes wrong (due to the inconsistent nature of python script exiting, even with the `throw()` function). I feel I may have to also look into producing nodejs scripts that achieve the same goals (luckily, there is an [SDK for that too](https://github.com/aws/aws-sdk-js-v3)) but I will reserve that thought until after I [build the website skeleton](https://github.com/M-Davies/eye-of-horus/issues/3)

**Comment by M-Davies** [comment]
Moved milestone ahead

**Comment by M-Davies** [comment]
NodeJS has been instantiated for the website backend side and it's been decided in [my latest blog](https://dle.plymouth.ac.uk/mod/oublog/viewpost.php?post=3411) to use boto for most of the heavylifting. Facial recog scripts are in place but need testing

**Comment by M-Davies** [comment]
New spinoff issues for this epic -> https://github.com/M-Davies/eye-of-horus/issues?q=is%3Aissue+is%3Aopen+label%3Aface

**Comment by M-Davies** [comment]
Python script are functional! We just need the website to hook them up to a nice UI now :)
